
# unset GTK_PATH

PP = ./../LngHandler/bin/ppp

EX = ./../LngHandler/bin/cpu
AS = ./../LngHandler/bin/asm
BT = ./../LngHandler/bin/bin_translator

compile :
	$(PP)
	./../LngHandler/bin/cpu a.code

bin : 
	$(BT) a.code	

